web-ridge/react-native-paper-dates

README.md
example/src/App.tsx
src/Date/DatePickerModal.tsx

Closes #21
I hope it ok that I created a PR directly to development branch

Add explicit animationType for DatePickerModal

---

example/src/App.tsx
example/tsconfig.json
src/Date/Calendar.tsx
src/Date/DatePickerModal.tsx
src/Date/DatePickerModalContent.tsx
src/Date/DatePickerModalContentHeader.tsx
src/Date/Month.tsx

This PR plans to add multiple date support, to close #43.
@RichardLindhout Can you confirm that we can close this if I can get it done and make it work well?
Thanks!

Support multiple date selection

---

src/Date/CalendarEdit.tsx

There is an issue that occurs (might only be in Western Hemisphere) where the date always becomes Nov 30th
It's because the inputDate string replacement does not happen because `new Date(Date.UTC(2020, 10 - 1, 1))` in Western Hemisphere is the previous day so `'10'`  and `'01'`  are not found in `inputDate` and are not replaced, as a result `dayIndex` and `monthIndex` (lines 160 and 161) are evaluated to `-1`
[Previous behaviour](https://www.loom.com/share/91f0db6feb6e4030a2cfdf0c2b67c058)
[Corrected behaviour](https://www.loom.com/share/3328c3c07e9249bfb0e1bff30e087c22)

fix: input date issue

---

src/Date/CalendarEdit.tsx
src/Date/DatePickerModalContent.tsx

Locale property was defined for DatePickerModal component, but not passed down to CalendarEdit. CalendarEdit needs locale for proper input format detection.

fix: pass locale property to CalendarEdit

---

src/Time/AnalogClock.tsx
src/Time/AnalogClockHours.tsx
src/Time/AnalogClockMinutes.tsx
src/Time/TimePicker.tsx
src/Time/timeUtils.ts

Fixed require cycle warning

---

src/Date/CalendarHeader.tsx
src/Date/DatePickerModalContentHeader.tsx
src/Date/DatePickerModalHeader.tsx
src/Date/Day.tsx
src/Date/Month.tsx
src/Date/YearPicker.tsx
src/translations/en.ts
src/translations/enGB.ts
src/translations/utils.ts

This PR makes some buttons in the app more accessible, by marking them as buttons for the sake of accessibility, and by providing text labels for them. The specific use case I'm working with is iOS Voice Control, which lets you tap items on the screen based on their name.
Voice Control provides a names overlay to make it easy to visualize what elements have which names. Before this PR the overlay shows:
Note that:
- Most icon buttons don't have a label
- Days of the month and the year dropdown aren't indicated as buttons at all
After this PR, the overlay shows:
Note that I haven't added accessibility to all components in the app, just the ones I have experience with from the app I'm using RN Paper in.
Thanks for the great library!

Button accessibility

---

README.md
example/src/App.tsx
example/src/ReadMeExampleMultiple.tsx
example/src/ReadMeExampleRange.tsx
example/src/ReadMeExampleSingle.tsx
src/Date/DatePickerModalContent.tsx
src/Date/DatePickerModalContentHeader.tsx
src/Date/DatePickerModalHeader.tsx
src/Time/TimePickerModal.tsx

Pull request in response to issue #119 if it is decided this should be added.
- This PR introduces an `uppercase` prop for calendar and time modals.

Introduce uppercase prop.

---

src/translations/de.ts

The messages for mustBeHigherThan and mustBeLowerThan could be improved somewhat by being able to add the date in the middle i.e.
```
mustBeHigherThan: (date: Date) => `Muss nach dem ${date} sein`,
mustBeLowerThan: (date: Date) => `Muss vor dem ${date} sein`,
```
But it's a rather minute improvement that wouldn't be worth it if it means a lot of effort in the code.

Add german translations

---

src/Date/dateUtils.tsx
src/Date/inputUtils.ts

Hello! In Portuguese they use `AAAA` instead of `YYYY` for dates. This PR updates the inputFormat to use `AAAA` when the Portuguese locale is selected.

fix: update input label for pt locale

---

src/Time/AnalogClock.tsx

All Submissions:
New Feature Submissions:
Changes to Core Features:
Fixes web-ridge/react-native-paper-dates#132

fix(time-picker): Unable to select any hours before noon, #132

---

src/Time/TimeInputs.tsx

Hey, in the time picker component when in keyboard mode it allows setting the minutes to 60, but the correct is up to 59 minutes max.

Fixed 60 Minutes, it should be 59 Minutes

---

README.md

Expo instruction incomplete if expo-localization is not installed.

update: expo instructions were incomplete

---

src/translations/ko.ts

This PR adds Korean translations for the 'ko' locale.

Add korean translations

---

README.md
example/src/App.tsx
example/src/ReadMeExampleMultiple.tsx
example/src/ReadMeExampleRange.tsx
example/src/ReadMeExampleSingle.tsx
src/Date/Calendar.tsx
src/Date/DatePickerModalContent.tsx
src/Date/YearPicker.tsx

Introduce start and end year props.

---

README.md
example/src/ReadMeExampleMultiple.tsx
example/src/ReadMeExampleRange.tsx
example/src/ReadMeExampleSingle.tsx
src/Date/DatePickerModalContent.tsx
src/Date/DatePickerModalHeader.tsx

- Introduces new `saveLabelDisabled` prop.

Introduce new saveLabelDisabled prop.

---

src/TextInputMask.tsx

Thanks for this amazing project!! 
------------------
PR INCLUDES:
A fix for this issue: #98 
Solves issues: 
- By selecting the manual date selection tool and updating the textInput component, if we start updating the text from the middle, the state updating will cause the cursor to jump to the end of the text. By updating the local state and mask properly onBlur, we will prevent this problem
Before: 
https://user-images.githubusercontent.com/60409704/197133897-9ab6c1e8-bfb5-4a3e-9c69-ba5fb9fa72cc.mov
After: 
https://user-images.githubusercontent.com/60409704/197134034-085e45f0-f7f8-4b3a-9702-25e4393ef8a7.mov

Fixing jumping to the end on textinput

---

src/Date/DatePickerInputWithoutModal.tsx

Looks like there was still an issue in `0.9.0`.

Resolve misaligned text.

---

README.md
src/translations/it.ts

This PR adds Italian translations for the 'it' locale.

Add Italian translations

---

.github/workflows/check-repro.yml
.github/workflows/stale.yml
.github/workflows/traige.yml

Alleviate some manual checks by letting automated jobs handle this for us. This pull request introduces three actions to do just that. They are as follows:
1. Check Repro - The github action for checking if issue author presented the repro.
2. Stale - Mark issues with no repro/response as stale.
3. Triage - The GitHub action will comment on any issue when you add a label (currently needs more info and needs repro). This can be helpful to not have to write a descriptive message every time when asking for more details.

Add automated checks to make our lives easier.

---

example/src/App.tsx
src/Time/AmPmSwitcher.tsx
src/Time/AnalogClock.tsx
src/Time/AnalogClockHours.tsx
src/Time/AnalogClockMinutes.tsx
src/Time/TimeInput.tsx
src/Time/TimeInputs.tsx
src/Time/TimePicker.tsx
src/Time/TimePickerModal.tsx
src/Time/timeUtils.ts
src/__tests__/Date/DatePickerInput.test.tsx
src/__tests__/Date/DatePickerInputWithoutModal.test.tsx
src/__tests__/Date/__snapshots__/DatePickerInput.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModa.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap
src/__tests__/Time/AmPmSwitcher.test.tsx
src/__tests__/Time/__snapshots__/AmPmSwitcher.test.tsx.snap
src/__tests__/Time/__snapshots__/AnalogClock.test.tsx.snap
src/__tests__/Time/__snapshots__/AnalogClockHours.test.tsx.snap
src/__tests__/Time/__snapshots__/AnalogClockMinutes.test.tsx.snap
src/__tests__/Time/__snapshots__/TimeInput.test.tsx.snap
src/__tests__/Time/__snapshots__/TimeInputs.test.tsx.snap
src/__tests__/Time/__snapshots__/TimePicker.test.tsx.snap
src/utils.ts

@RichardLindhout I think this is ready to look at, but please check it out. I think it's headed in the right direction.
Our library supports Material 3, but lacks the proper specs for the [Time Picker](https://m3.material.io/components/time-pickers/specs) according to MD3 documentation. This pull request is created to address the initial upgrades for only the Time picker. It's not perfect, but this can serve as the baseline. @RichardLindhout I'll leave the Date Picker for you :). It seems more involved and might cause us to have separate pickers for between version 2 and 3. I'd be glad to discuss a plan of attack on this.
https://user-images.githubusercontent.com/7604441/209482428-2d85e96e-b9ea-4c16-9e41-03abf88fb50b.mov

Update time picker to material 3 specs.

---

docusaurus/docs/date-picker/input-date-picker.md
src/Date/DatePickerInput.shared.tsx
src/Date/DatePickerInput.tsx
src/Date/DatePickerInputWithoutModal.tsx
src/Date/inputUtils.ts
src/TextInputMask.tsx
src/__tests__/Date/__snapshots__/AnimatedCrossView.test.tsx.snap
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInput.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap

The `DatePickerInput` does not give the flexibility to roll out your own validation (ex. if a user selected date of birth is older than 18 years) which could result in two `helperText` errors being shown under the `DatePickerInput`.
This PR introduces a few new props `hideValidationErrors`, `hasError`, and `onValidationError`, etc in order to provide the ability to ingest the internal validation errors from the component, hide the components error styles, and give the developer the option of rolling out there own validation.
_The developer docs are updated as well to have all the new props along with some other missing props._

Date input props

---

src/Date/DatePickerInput.tsx

When the `disabled` prop is passed to the `DatePickerInput` the `IconButton` is not also disabled. This pull request passes the disabled prop along to the `IconButton`, so that the entire component will become disabled is specified.

Pass disabled to icon button.

---

src/Time/AnalogClock.tsx
src/Time/AnalogClockHours.tsx
src/__tests__/Time/__snapshots__/AnalogClock.test.tsx.snap
src/__tests__/Time/__snapshots__/AnalogClockHours.test.tsx.snap

1. As part of the ticket above I noticed 00 is appearing twice in the clock. Its correct appearance should be as follows with "00" and "12". That is addressed as part of this.
2. "00" was also appearing in the 12 hour clock which isn't standard. According to the [material 3 docs](https://m3.material.io/components/time-pickers/guidelines#e72059b2-d772-456b-bbc7-bd8aeed0144f) it should be 12 instead. This is addressed as part of this.
@RichardLindhout  Please test and verify existing functionality still behaves as expected.

24 hour bug

---

docusaurus/docs/time-picker.md
src/Time/TimeInput.tsx
src/Time/TimeInputs.tsx
src/Time/TimePicker.tsx
src/Time/TimePickerModal.tsx

1) Our "is 24 hour clock setting" is different than the phone setting so we needed a property to change it.
2) We use a custom font that is bigger and at the current size (57) numbers were not fitting in the defined height (72-80)

feat: Enable changing the input font size and the 24 hour mode

---

example/package.json
example/yarn.lock
src/Date/DatePickerInput.shared.tsx

[Expo 48 ](https://blog.expo.dev/expo-sdk-48-ccb8302e231) is now available and in order to stay ahead of the curve this pull request updates the example app to use the latest SDK. We can and should consider updating the library dependencies to RN 71+, but we can save that for another pull request.
**Note: It also contains the same small fix in https://github.com/web-ridge/react-native-paper-dates/pull/262, which you can see for more details.**

chore: Update example app to use Expo 48.

---

src/Date/DatePickerInput.shared.tsx

Addresses typescript issues that will arise when we update to react native 71 and Expo 48. Confirmed it still has backward compatibility, but feel free to verify.
More details are described in this [discussion](https://github.com/web-ridge/react-native-paper-dates/discussions/261). In short it looks like once we update the `inputMode` props overlap causing the entire type to become `never`.

Fix overlapping attributes.

---

example/src/App.tsx
src/Date/DatePickerModalContent.tsx
src/Date/DatePickerModalContentHeader.tsx
src/__tests__/Date/__snapshots__/AnimatedCrossView.test.tsx.snap
src/__tests__/Date/__snapshots__/Calendar.test.tsx.snap
src/__tests__/Date/__snapshots__/YearPicker.test.tsx.snap

This PR fixes some issues related to the `allowEditing` prop that was recently added to the Date Picker Header:
1. Prevents it from being always `true` regardless the value that was actually passed.
2. Uses the `allowEditing` prop correctly to decide if the edit button should be displayed or not. Before, an unused `inputDate` prop, which was always undefined, was making the edit button not to be rendered at all, regardless of the props being passed to the component for this purpose.

Fix the allowEditing prop which was being accidentally ignored

---

src/Date/DayRange.tsx

Before
After
Note - There are no guidelines on selecting a range to itself, but this is a potential existing style bug, that I noticed while playing around trying to fix this issue. @RichardLindhout Let me know your thoughts on this.

Fix date range gap.

---

src/TextInputMask.tsx
src/__tests__/Date/__snapshots__/AnimatedCrossView.test.tsx.snap
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInput.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap

@RichardLindhout Please test this out and make sure it works how we discussed.
@jpatricksweeney This isn't quite ready yet. It doesn't accommodate all scenarios. You might be able to use [patch-package](https://github.com/ds300/patch-package#readme) to apply this temporarily since not everyone uses the slash in there date representation.
**NOTE - Invalid dates of 00/00/0000 and 99/99/9999 can be input, but it doesn't cause any issues. The validation seems to gracefully handle this scenario.**

Introduce auto slashes to text input.

---

src/TextInputMask.tsx

**Issue:**
When the locale of the DatePickerInput component is set to "de" (German), the functionality to add an automatic date separator ("." in the case of the German locale) is broken. Instead of appending a dot to the first two characters entered, the input gets changed to a single dot. Subsequently, any numbers entered are concatenated without the proper separator.
**Solution:**
I found the usage of the `RegExp` constructor to create regular expressions. One of the supported date separator is `.` (dd.mm.yyyy). The `dot` character is a `metacharacter` in regular expressions which needs to be escaped if it is being passed into the `RegExp` constructor. In this code block, it was not escaped. Hence the code 
```JS
new RegExp('.', 'g')
```
yielded a different regex than the expected one. …

Fix for passing dot as splitcharacter to RegExp constructor

---

src/Date/DatePickerModalHeader.tsx

Trying to find a solution for the issue #309, I found this unnecesary code.
The `fill`style was not using and the prop `color` was deprecated and now is `textColor`.

style: removed unnecessary code

---

docusaurus/docs/date-picker/input-date-picker.md
docusaurus/docs/date-picker/multiple-dates-picker.md
docusaurus/docs/date-picker/range-date-picker.md
docusaurus/docs/date-picker/single-date-picker.md
src/Date/DatePickerModal.tsx

PresentationStyle

---

src/Date/DatePickerInput.shared.tsx
src/Date/DatePickerInput.tsx
src/Date/DatePickerInputWithoutModal.tsx
src/TextInputMask.tsx
src/__tests__/Date/__snapshots__/AnimatedCrossView.test.tsx.snap
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap

Fix #298.
@RichardLindhout @iM-GeeKy 
I have changed different parts but the most important and the main problem for the alignment was the position absolute for the icon when you have in `react-native-paper` the option to add directly the icon in the right side and centered of the TextInput. Using the way of `react-native-paper`  will be centered by default
Here I attach a gif showing the currently position and will see a little movement (to the left and top)
This is because I changed between branchs to show the differences and is minimal and for that maybe it's more visible show it in this way:
I did and tested in Linux.  I tried to test in Windows but [you have another problem there](https://github.com/web-ridge/react-native-paper-dates/issues/314).
If someone can test, will be great. …

fix alignment calendar icon

---

docusaurus/docs/date-picker/input-date-picker.md

Added `validRange` prop in the `input-date-picker` docs.

docs: Added validRange prop

---

src/Date/DatePickerModal.tsx

Fix #309
After a lot of research, the problem was the `Statusbar`.
I don't know if is the best solution but works.
Now the modal opens fluently

Fixed Datepicker modal jump when is opened

---

docusaurus/docs/date-picker/input-date-picker.md
docusaurus/docs/date-picker/multiple-dates-picker.md
docusaurus/docs/date-picker/range-date-picker.md
docusaurus/docs/date-picker/single-date-picker.md
src/Date/DatePickerInput.shared.tsx
src/Date/DatePickerInput.tsx
src/Date/DatePickerInputWithoutModal.tsx

chore: add disableStatusBarPadding to date picker input

---

docusaurus/docs/contributing.md

As we discussed in this [issue](https://github.com/web-ridge/react-native-paper-dates/issues/314) I have added a note in contributing guide explaining how to make yarn usable on a windows machine.
**Final result**

Added note in contributing guide explaining how to make yarn usable on a windows machine

---

src/Date/DatePickerInputWithoutModal.tsx
src/__tests__/Date/__snapshots__/AnimatedCrossView.test.tsx.snap
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap

This PR addresses [324](https://github.com/web-ridge/react-native-paper-dates/issues/324).

Added web responsiveness back to date input field

---

src/Date/DatePickerInputWithoutModal.tsx
src/__tests__/Date/__snapshots__/AnimatedCrossView.test.tsx.snap
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap

Fix #324 
The PR https://github.com/web-ridge/react-native-paper-dates/pull/326 had generated an overflow.
This fix solves the problem and works perfectly (Tested in Android and Web)

chore: Fixed responsiveness DatePickerInput

---

docusaurus/docs/time-picker.md
src/Time/TimePickerModal.tsx

fixes: https://github.com/web-ridge/react-native-paper-dates/issues/330
TimePickerModal now accepts a prop `defaultInputType`, which can be used to set which input is shown first.

Default input type for time picker

---

src/Time/AmPmSwitcher.tsx
src/Time/AnalogClock.tsx
src/Time/TimePicker.tsx
src/contexts/DisplayModeContext.tsx

Fix https://github.com/web-ridge/react-native-paper-dates/issues/313
@SoyDiego

chore: fix require cycle warning

---

docusaurus/docs/date-picker/input-date-picker.md
src/Date/DatePickerInput.shared.tsx
src/Date/DatePickerInput.tsx

add animationType to DatePickerInput

---

src/Date/DatePickerInput.shared.tsx
src/Date/DatePickerInput.tsx

Added prop presentationStyle in DatePickerInput
For iOS especially sometimes the Modal is behind the Notification bar and is not clickable to close or save. Using 
presentationStyle="pageSheet" 
we can configure it to show up as sheet on iOS

Added prop presentationStyle in DatePickerInput

---

src/Time/TimeInputs.tsx
src/Time/TimePicker.tsx
src/translations/ar.ts
src/translations/ca.ts
src/translations/cs.ts
src/translations/de.ts
src/translations/el.ts
src/translations/en.ts
src/translations/enGB.ts
src/translations/es.ts
src/translations/fr.ts
src/translations/he.ts
src/translations/hi.ts
src/translations/it.ts
src/translations/ko.ts
src/translations/nl.ts
src/translations/pl.ts
src/translations/pt.ts
src/translations/ro.ts
src/translations/ru.ts
src/translations/tr.ts
src/translations/utils.ts
src/translations/zh.ts
src/translations/zhTW.ts

This pull request aims to add translations for the words 'Hour' and 'Minute' in the `TimeInputs` component of the library.
Previously, these words were in English regardless of the language set in the application. With this change, the user experience is improved by providing a consistent and fully translated user interface.
Changes made:
- Added translations for 'Hour' and 'Minute' in the `TimeInputs` component.

Add translations for 'Hour' and 'Minute' in TimeInputs component

---

.husky/pre-commit
example/package.json
example/yarn.lock
package.json
src/__tests__/Date/__snapshots__/AnimatedCrossView.test.tsx.snap
src/__tests__/Date/__snapshots__/Calendar.test.tsx.snap
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap
src/__tests__/Date/__snapshots__/YearPicker.test.tsx.snap
yarn.lock

@RichardLindhout If you wouldn't mind regression testing this it would be appreciated. Things appeared to work as expected on the surface, but a lot of packages were upgraded to their next major version which could bring about break changes! Once, this is merged I'll look to bump the snack versions as well.

refactor: bump all packages to latest version

---

src/Time/TimePickerModal.tsx

The current time picker modal is not rounded (square) for version 3, so it is now set to 28 per the specs. I'm not sure if it'd be more beneficial to use `theme.roundness`, but then it would have to be dynamically calculated.

fix: add correct roundness to time picker modal

---

src/Time/TimePickerModal.tsx

https://github.com/web-ridge/react-native-paper-dates/commit/e9d69556b50cdf5df70c6df440818d6b3454e387 introduced a bug where if the app is using a Material V2 dark theme, the time picker will access a color property which isn't defined, resulting in a hard crash with a "Cannot read property 'level3' of undefined". 
This is due to the previous logic gating on `theme.isV3` before accessing the property, while the current logic does not gate on this. 
This PR changes the logic to be similar to the change to [Day.tsx](https://github.com/web-ridge/react-native-paper-dates/commit/e9d69556b50cdf5df70c6df440818d6b3454e387#diff-a9529d1fba70bb307f3d24f1b57f81660d2a9cb03e7a9a86c2cd63bde46e09d0), which does check if the theme is V3 before accessing potentially undefined properties.
We have deployed …

Fix v2 dark theme

---

src/Date/DatePickerInput.tsx

When using TextInput.Icon and a DatePicker modal on slower devices, a virtual keyboard briefly appears due to premature input focus. To address this, I propose adding a forceTextInputFocus prop with a value of false. This change should prevent the keyboard from showing up unnecessarily.

Fix keyboard flash issue with TextInput.Icon and DatePicker modal

---

src/Date/dateUtils.tsx

This backs out the change made in https://github.com/web-ridge/react-native-paper-dates/issues/383 as it breaks some of the other modal modes. I will rework the logic and create another PR when it is fixed and stable.

revert: performance fix for multiple ios until better solution found

---

example/package.json
example/webpack.config.js
example/yarn.lock

The `deploy-example` pipeline is failing and spitting out
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'crypto' in '/home/runner/work/react-native-paper-dates/react-native-paper-dates/example/node_modules/expo-modules-core/build/uuid'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "crypto": false }
```
This is an attempt to potentially fix that based on the suggested …

refactor: attempt to resolve example ci failure

---

.github/workflows/ci.yml
example/package.json
example/webpack.config.js
example/yarn.lock

This fixes the `deploy-example` pipeline which has been failing for some time. Let's get all of our pipelines back to successfully running!
The fixed if based off of the pipeline error
```
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "stream": false }
ModuleNotFoundError: Module not found: Error: Can't resolve 'stream' in '/home/runner/work/react-native-paper-dates/react-native-paper-dates/example/node_modules/cipher-base'
```

Fix ci example deploy

---

src/Time/TimeInput.tsx

When trying to remove values ​​in the textinput hour or minute in keyboard type the string comparison is not working correctly
3:15
Removing the 3, the string parameter will be empty in the event

TextInput string to number

---

src/Date/CalendarEdit.tsx
src/Date/DatePickerInput.tsx
src/Date/DatePickerModal.tsx
src/Date/DatePickerModalContent.tsx
src/Date/DatePickerModalContentHeader.tsx

As described in [https://github.com/web-ridge/react-native-paper-dates/issues/430](https://github.com/web-ridge/react-native-paper-dates/issues/430)
- `withDateFormatInLabel` is now being used in the edit-input-field
- `placeholder` is now being used in the edit-input-field

Fix edit-input-field to respect disabling format in label and placeholder

---

src/Date/dateUtils.tsx

trunc the ms instead of round to avoid edge cases where the date would be changed example:  Math.round((new Date('2024-12-10T23:59:59.999Z')).getTime() / 1000) vs
Math.trunc((new Date('2024-12-10T23:59:59.999Z')).getTime() / 1000)

fix: dateToUnix to preserve the date #434

---

src/Date/DatePickerModal.tsx

This PR sets better defaults for the `DatePickerModal` on larger screens. It makes it look more inline with Material modals.
It changes the modal which looks like this:
To this:

fix: more sensible date modal styles

---

src/Date/AutoSizer.tsx
src/Date/DatePickerModalContentHeader.tsx

This fixes issue #442 (Or a similar problem).
onLayout on Android does not always set the correct value immediately. To fix this, I suggest using a slightly different condition for rendering and setting the size. If the height or width is 0, we assume that the layout has not been calculated yet.
I tested this on a Redmi Note 11E Pro device in the release version. Expo: 52.0.36, RN: 0.77.1 
This probably eliminates the effect, not the cause. But since it's difficult to analyze because the bug is floating, I decided to propose such changes.
**before:**
https://github.com/user-attachments/assets/deeb5dab-1562-4dd6-a67d-3e578ee8b3eb
**after:**
https://github.com/user-attachments/assets/76f4e652-e59d-4f6c-805b-2f2fa35df1ae
<details>
<summary>My test code</summary>
```typescript
export default …
```

fix: Pixel 8a and 9 series sometimes do not render the calender #442

---

.github/workflows/ci.yml
package.json
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInput.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap

This just fixes the `deploy-example` and `test` pipeline that broke somewhere along the line. All pipelines should successfully complete now and we will get the latest web app deployed 😎

Fix deploy example pipeline

---

docusaurus/docs/intro.md
src/translations/utils.ts

In some use cases, other i18n solutions manage translations. In these cases, it is desirable to resolve the translations dynamically.
For example, I use [tolgee](https://tolgee.io/) as a way to create and manage translations. It already deals with resolving the locale, and potentially pulling new translations from a remote server. As such, it is not feasible to know the translations at build or app start time, or even resolve them immediately without using a fallback.
This PR just adds a mechanism to provide a function to the `registerTranslation` function, which will be called when getting the translation.
In my application, this looks like this:
```typescript
import { registerTranslation } from 'react-native-paper-dates';
import { tolgee } from '@/services/tolgee'; …
```

Allow registering dynamic translations

---

docusaurus/docs/date-picker/input-date-picker.md
docusaurus/docs/date-picker/multiple-dates-picker.md
docusaurus/docs/date-picker/range-date-picker.md
docusaurus/docs/date-picker/single-date-picker.md
docusaurus/docs/time-picker.md
src/Date/DatePickerInput.shared.tsx
src/Date/DatePickerInput.tsx
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInput.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap

This introduces a new `disableCalendarIcon` prop that defaults to `false` for the `DatePickerInput` that can be used and while updating the docs I alphabetized the props for the other component documentation files to improve readability.

disableCalendarIcon prop for DatePickerInput

---

example/babel.config.js
example/package.json
example/webpack.config.js
example/yarn.lock
package.json
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInput.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap
yarn.lock

close https://github.com/web-ridge/react-native-paper-dates/issues/482
In addition, I alphabetized the attributes in the json files to improve readability and maintainability.

Icons work in web for example app

---

src/Date/Swiper.tsx
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInput.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap

Continuation of https://github.com/web-ridge/react-native-paper-dates/issues/482. The calendar days are now rendering on web.

Dates and month for multiple and range picker rendering on web

---

src/Time/TimePickerModal.tsx
src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInput.test.tsx.snap
src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap

- Fixes https://github.com/web-ridge/react-native-paper-dates/issues/487#issue-3249930565 by updating min width to account for am/pm selector.
- Fixes the broken tests in https://github.com/web-ridge/react-native-paper-dates/pull/496 so we can close that. Thanks @newclarityex 😎

refactor: fix overflow issue on time picker modal
