web-ridge/react-native-paper-dates

src/Date/CalendarEdit.tsx
Added a error text to show the date format
Closes #45
=> Fixed the crash on input mode

src/Date/Calendar.tsx, src/utils.ts
the default lighten method has issue where it returns white (#ffffff) instead of lighten color
https://github.com/Qix-/color/issues/53
Closes #85
=> fix: Modify logic to lighten and darken colors

example/src/App.tsx, example/src/ReadMeExampleDatePickerInput.tsx, jest.config.js, package.json, src/Time/AnalogClock.tsx
All Submissions:
New Feature Submissions:
Changes to Core Features:
PS : I added two ts-ignore that we should fix in the future, I'll try to spend some time on writing tests for the lib.
Fixes web-ridge/react-native-paper-dates#97
=> fix(analog-clock): add condition when selecting am 12 to return 00:00

src/translations/utils.ts
Replace translationForLocale with translation on line 34
=> Update utils.ts (#1)

README.md, src/Date/DatePickerInput.tsx, src/Date/DatePickerModalContent.tsx, src/Date/DatePickerModalContentHeader.tsx, src/Date/DatePickerModalHeader.tsx, src/Date/DateRangeInput.tsx, src/Time/TimePickerModal.tsx, src/Time/timeUtils.ts
=> feat: icon name props for date and time pickers

README.md, src/translations/ar.ts
This PR adds Arabic translations for the 'ar' locale.
=> Add Arabic translations 

src/Date/DatePickerInput.tsx
=> Resolved misaligned helper text.

README.md, src/translations/es.ts
this pr add spanish translations
=> Add Spanish translations

src/Date/DatePickerModalContent.tsx, src/Date/DatePickerModalHeader.tsx
=> Fix uppercase and disabled prop not taking.

src/Time/AnalogClock.tsx, src/Time/AnalogClockHours.tsx, src/Time/timeUtils.ts, src/__tests__/Time/__snapshots__/AnalogClock.test.tsx.snap, src/__tests__/Time/__snapshots__/AnalogClockHours.test.tsx.snap, src/__tests__/Time/timeUtils.test.tsx
=> Roll out fixes for 12 hour formatting.

src/Time/timeUtils.ts, src/__tests__/Time/timeUtils.test.tsx
=> AM/PM Time bug.

src/Date/YearPicker.tsx
=> fix: Update text color related to issue #277.

docusaurus/docs/intro.md, example/src/App.tsx, src/index.tsx, src/translations/ca.ts
- Added catalan translations
- Updated the documentation
=> Added catalan translations

docusaurus/package.json, docusaurus/yarn.lock
Should fix https://github.com/web-ridge/react-native-paper-dates/actions/runs/6560315338/job/17817672991
=> chore: add color

package.json
=> chore: bump version to fix pipeline

src/Date/DatePickerInput.tsx, src/Date/DatePickerModal.tsx
I added a conditional to avoid the problem. I tested in Android and works perfectly.
Maybe you can check @iM-GeeKy in `iOS` if you can see the warning.
Thanks!
=> Fix presentationStyle warning

src/Date/Month.tsx
Replaced IconButton with Icon component
=> fix: validateDOMNesting

src/Date/DayRange.tsx
closes https://github.com/web-ridge/react-native-paper-dates/issues/380
=> refactor: fix date range overflow issue

src/Date/dateUtils.tsx
Closes https://github.com/web-ridge/react-native-paper-dates/issues/383
https://github.com/user-attachments/assets/da1b2335-e34f-441d-9d4c-cd821ef7c9a7
=> Fixed performance issue on ios comparing dates using multiple mode

example/src/App.tsx
The example app layout is not consistent on tablets as seen in the image below.
Updated the styles so that the layout is now consistent on all viewports (mobile, tablet, web).
=> refactor: fixed layout for tablet views

src/translations/en.ts, src/translations/enGB.ts
Just a quick fix for a small typo — changed "then" to "than" in the message "date must be later than other".
=> Fix validation grammar for english

package.json, src/__tests__/Date/__snapshots__/CalendarEdit.test.tsx.snap, src/__tests__/Date/__snapshots__/DatePickerInput.test.tsx.snap, src/__tests__/Date/__snapshots__/DatePickerInputWithoutModal.test.tsx.snap
This aims to fix the pipeline so when pull requests are merged into master all automated tasks operate as expected. The test and release pipelines are the ones that this attempts to resolve.
=> Bump version to not deploy over existing version and fix tests
